### ISSUE TITLE
Docker containers don't run as advertised from blog post

### ISSUE THREAD

**Issue by ddelnano** [pennyphp/bookshelf#1]
I was attempting to follow your blog post, however, when running `docker-compose build` there does not exist a Dockerfile in the `docker/development/nginx/` directory so it fails.  I added a simple Dockerfile like the following:

```
FROM fntlnz/nginx:1.8.0
```

However it has a problem accessing redis after being able to build.

**Comment by fntlnz** [comment]
Hi! I forgot to update the `docker-compose.yml.development` to use the `fntlnz/nginx:1.9.5` image.
I pushed a change to it [a few minutes ago](https://github.com/pennyphp/bookshelf/blob/master/docker/docker-compose.yml.development#L2)

I also made some changes to the php-fpm dockerfile so I suggest you to do the following

``` bash
git pull
cp docker/docker-compose.yml.development docker-compose.yml
docker-compose build
docker-compose up
```

For redis it's possible that you haven't created the `redis.local.php` under the `config/` folder?
You can create it with a `cp config/redis.local.php.dist config/redis.local.php`

Thank you for your feedback!

**Comment by ddelnano** [comment]
No problem and yea I figure that out about the redis.  At first I didn't want to read through all the DI code so I just hard coded it to get it to work.
