### ISSUE TITLE
ClassicApp namespace

### ISSUE THREAD

**Issue by fntlnz** [pennyphp/bookshelf#5]
All things under the `app/` folder still belongs to the `ClassicApp` namespace that has been inherited from the `penny-classic-app` from which this demo has been derived.

**Comment by gianarb** [comment]
can We replace it with `Bookshelf`?

**Comment by samsonasik** [comment]
generic `App` is ok for me

**Comment by fntlnz** [comment]
@samsonasik yeah, as you said `App` is better for me too.

**Comment by samsonasik** [comment]
cool, let's do it ;)

**Comment by samsonasik** [comment]
I've created PR #6 for it ;)

**Comment by gianarb** [comment]
:+1:

**Comment by fntlnz** [comment]
And IMO this should apply also to the penny-classic-app project in order to not bore the final developer :D

**Comment by samsonasik** [comment]
done https://github.com/pennyphp/penny-classic-app/pull/37 ;)

**Comment by fntlnz** [comment]
:D

**Comment by samsonasik** [comment]
all accomplished, closing it ;)
